replicaCount: 3

image:
  repository: ghcr.io/ivegotahunnitonit/bartholomew
  pullPolicy: IfNotPresent
  tag: "6.4.3"

service:
  type: ClusterIP
  port: 8080

datacenter:
  enabled: true
  enclaveAttestation:
    enabled: true
    goldenPcr0Verification: true
  ebpfDaemon:
    enabled: true
    mode: "RING0_POSIX"
    interceptSyscalls:
      - sys_enter_execve
      - sys_enter_connect
      - sys_enter_openat
      - sys_enter_ptrace
  quotas:
    defaultMemoryMb: 2048.0
    defaultEgressKb: 100000.0

ast:
  subMicrosecond: true
  maxLatencyUs: 35
  zeroPhoneHome: true
  strictInvariants: true

telemetry:
  egress: false
  format: rfc8785-canonical-json
  signature: ed25519

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  allowPrivilegeEscalation: false
